//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsignmentShopLibrary.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConsignmentShopLibrary.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BEGIN TRANSACTION;
        ///CREATE TABLE IF NOT EXISTS &quot;Items&quot; (
        ///	&quot;Id&quot;	INTEGER NOT NULL,
        ///	&quot;Name&quot;	NVARCHAR(200) NOT NULL,
        ///	&quot;Description&quot;	NVARCHAR(2000),
        ///	&quot;Price&quot;	MONEY NOT NULL,
        ///	&quot;Sold&quot;	BIT NOT NULL,
        ///	&quot;OwnerId&quot;	INT NOT NULL,
        ///	&quot;PaymentDistributed&quot;	BIT NOT NULL,
        ///	PRIMARY KEY(&quot;Id&quot; AUTOINCREMENT),
        ///	FOREIGN KEY(&quot;OwnerId&quot;) REFERENCES &quot;Vendors&quot;(&quot;Id&quot;)
        ///);
        ///CREATE TABLE IF NOT EXISTS &quot;Stores&quot; (
        ///	&quot;Id&quot;	INTEGER NOT NULL,
        ///	&quot;Name&quot;	TEXT NOT NULL,
        ///	&quot;StoreBank&quot;	MONEY NOT NULL,
        ///	&quot;StoreProfit&quot;	MONEY NOT NULL,
        ///	PRIMARY KE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateSQLiteDB {
            get {
                return ResourceManager.GetString("CreateSQLiteDB", resourceCulture);
            }
        }
    }
}
